baseurl = "https://noordkaap2022.onrender.com/"
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = "true"
title = "Noordkaap 2022"
theme = "hamburg"

[params]
    # Short subtitle/tagline. This is displayed in the header.
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
    # To load additional CSS styles
    #customCSS = ['hamburg.css']
    # Show this very user-friendly and absolutely not annoying GDPR notice at the bottom of the page
    ShowGDPRNotice = true
    subtitle = "Motorreis naar de Noordkaap"
	# Since 0.57.0 there's the concept of "main sections". The files for the section "posts" are in "./content/posts/".
    mainSections = ["posts"]

[languages]
    [languages.nl]
        languageCode = "nl"
        languageName = "Nederlands"
        #contentDir="content/nl"
        subtitle = "Motorreis naar de Noordkaap"
        copyright = "&copy; www.opfietse.net"
        [languages.nl.menu]
            [[languages.nl.menu.main]]
                name = "Over"
                identifier = "about"
                url = "pages/about"
            [[languages.nl.menu.main]]
                name = "Route"
                identifier = "route"
                url = "route/planned-route"
            [[languages.nl.menu.main]]
                name = "Posts"
                identifier = "posts"
                url = "posts"
    [languages.en]
        languageCode = "en"
        languageName = "English"
        #contentDir="content/en"
        title = "North Cape 2022"
        subtitle = "Motorcycle journey to the North Cape"
        # Copyright notice. This is displayed in the footer.
        copyright = "&copy; www.opfietse.net"
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "About"
                identifier = "about"
                url = "pages/about"
            [[languages.en.menu.main]]
                name = "Route"
                identifier = "route"
                url = "route/planned-route"
            [[languages.en.menu.main]]
                name = "Posts"
                identifier = "posts"
                url = "posts"
