baseURL: 'https://noordkaap2022.onrender.com/'
languageCode: 'nl-nl'
title: 'Noordkaap 2022'
theme: "ananke"
defaultContentLang: nl
languages:
  nl:
    contentDir: content/nl
    languageName: Nederlands
    title: Noordkaap 2022
    weight: 1
  en:
    contentDir: content/en
    languageName: English
    title: North Cape 2022
    weight: 2
